"""
Thin wrapper around an OpenAI-compatible Chat Completions API.

This module contains ZERO agent "intelligence" — it only knows how to send
a system/user prompt to whichever LLM endpoint is configured via `.env` and
return the raw text + token usage. Every decision, document, piece of code
or justification produced anywhere in Forge AI is generated by a real call
through this client — nothing is precomputed or hardcoded.
"""
from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from typing import Any

from openai import OpenAI

from config import settings


class LLMConfigurationError(RuntimeError):
    """Raised when the LLM cannot be called because .env is not configured."""


class LLMOutputError(RuntimeError):
    """Raised when the LLM returns output that cannot be parsed or is invalid."""


@dataclass
class LLMUsage:
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0

    def cost_usd(self) -> float:
        return (
            self.prompt_tokens / 1000 * settings.price_input_per_1k
            + self.completion_tokens / 1000 * settings.price_output_per_1k
        )


@dataclass
class LLMResult:
    content: str
    usage: LLMUsage = field(default_factory=LLMUsage)
    latency_seconds: float = 0.0
    model: str = ""


class LLMClient:
    """Shared by every agent to reach the real, configured LLM API."""

    def __init__(self) -> None:
        problems = settings.validate()
        self._configured = not problems
        self._problems = problems
        self._client: OpenAI | None = None
        if self._configured:
            self._client = OpenAI(
                api_key=settings.openai_api_key,
                base_url=settings.openai_base_url,
                timeout=settings.llm_timeout_seconds,
                max_retries=settings.llm_max_retries,
            )
        self.total_usage = LLMUsage()

    @property
    def is_configured(self) -> bool:
        return self._configured

    def configuration_problems(self) -> list[str]:
        return list(self._problems)

    def chat(
        self,
        system_prompt: str,
        user_prompt: str,
        *,
        json_mode: bool = False,
        temperature: float | None = None,
        max_tokens: int | None = None,
    ) -> LLMResult:
        if not self._configured or self._client is None:
            raise LLMConfigurationError("; ".join(self._problems) or "LLM is not configured.")

        kwargs: dict[str, Any] = dict(
            model=settings.openai_model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=temperature if temperature is not None else settings.llm_temperature,
            max_tokens=max_tokens or settings.llm_max_tokens,
        )
        if json_mode:
            kwargs["response_format"] = {"type": "json_object"}

        started = time.time()
        response = self._client.chat.completions.create(**kwargs)
        latency = time.time() - started

        content = response.choices[0].message.content or ""
        raw_usage = getattr(response, "usage", None)
        usage = LLMUsage(
            prompt_tokens=getattr(raw_usage, "prompt_tokens", 0) or 0,
            completion_tokens=getattr(raw_usage, "completion_tokens", 0) or 0,
            total_tokens=getattr(raw_usage, "total_tokens", 0) or 0,
        )
        self.total_usage.prompt_tokens += usage.prompt_tokens
        self.total_usage.completion_tokens += usage.completion_tokens
        self.total_usage.total_tokens += usage.total_tokens

        return LLMResult(content=content, usage=usage, latency_seconds=latency, model=settings.openai_model)

    def chat_json(
        self,
        system_prompt: str,
        user_prompt: str,
        *,
        retries: int = 2,
        temperature: float | None = None,
        max_tokens: int | None = None,
    ) -> tuple[dict[str, Any], LLMResult]:
        """Calls the LLM and guarantees a parsed JSON dict, asking the model
        to repair its own output if it produced invalid JSON."""
        last_result: LLMResult | None = None
        last_error: Exception | None = None
        prompt = user_prompt
        for _ in range(retries + 1):
            result = self.chat(
                system_prompt + "\nAlways respond with a single valid JSON object and nothing else. No explanation before or after.",
                prompt,
                json_mode=True,
                temperature=temperature,
                max_tokens=max_tokens,
            )
            last_result = result
            try:
                return json.loads(result.content), result
            except json.JSONDecodeError as exc:
                last_error = exc
                prompt = (
                    f"{user_prompt}\n\nYour previous reply could not be parsed as JSON "
                    f"({exc}). Reply again with ONLY a valid JSON object:\n{result.content}"
                )
        raise LLMOutputError(f"LLM did not return valid JSON after retries: {last_error}")


llm_client = LLMClient()
